---
title: "index"
author: "Stephanie"
date: "11/30/2017"
output: 
  html_document:
  code_folding: hide
  toc: true
  toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
```

## Gapminder

```{r}

gapminder<-readr::read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv")

## useful functions to get to know your data:
head(gapminder) ## show the first 6 rows of the data
tail(gapminder) ## show the last 6 rows of the data

head(gapminder, 30)

## check out the strucutre of your data
str(gapminder)

##column names
names(gapminder)

##dimensions of the data
dim(gapminder)
ncol(gapminder)
nrow(gapminder)

c(nrow(gapminder), ncol(gapminder))

summary(gapminder)

## For everything above we were operating on the the whole gapminder dataset.

head(gapminder$lifeExp)

```

## Actually working with dyplr

```{r}

filter(gapminder, lifeExp < 29)

filter(gapminder, country =="Mexico")

filter(gapminder, country == "Sweden")

Sweden <- filter(gapminder, country == "Sweden")

mean(Sweden$lifeExp)

## pipe operator %>%
## command-shift-M = %>% 

gapminder %>% head(3)

## instead of using 

head(gapminder, 3)

## will give you the same output

gapminder %>% filter(country== "Sweden") %>% 
  summarize(mean_lifeExp = mean(lifeExp))

```
## Select() by columns
```{r}

## Add use of the pipe operator

gapminder %>%
  select(year,lifeExp) %>%
  tail(6)

## Combine what we've learned

gapminder %>%
  filter(country =="Cambodia") %>%
  select(country, year, pop, gdpPercap)

## or use instead...it will give the same result

gapminder %>%
  filter(country =="Cambodia") %>%
  select (-continent, -lifeExp)

## a few more things with filter

gapminder %>%
  filter(country =="Mexico",
         year == 2002)

## 'mutate()' to add columns

gapminder %>%
  mutate(gdp = pop*gdpPercap)

## Add index column

gapminder %>%
  mutate(index = 1:nrow(gapminder)) %>%
  tail()

## Add index column and add a colum

gapminder %>%
  mutate(gdp = pop*gdpPercap) %>%
  mutate(index = 1:nrow(gapminder)) %>%
  tail()

## Pick two countries only, using %in% operatory lets you filer multiple thing within a c function i.e. c()

gapminder %>%
  filter(country %in% c("Egypt", "Vietnam"))


## Find the maximum gdpPercap of Egypt and Vietnam in a new column

gapminder %>%
  filter(country %in% c("Egypt", "Vietnam")) %>%
  mutate(max_gdpPercap = max(gdpPercap))


## Use group_by() function so that we can get the maximum from each of two countries

  gapminder %>%
  filter(country %in% c("Egypt", "Vietnam")) %>%
  group_by(country) %>%
  summarize(maxx_gdpPercap = max(gdpPercap))

## Do the same but will all countries

 gapminder %>%
  group_by(country) %>%
  summarize(max_gdpPercap = max(gdpPercap))

 ## Keep the year associated with that max_gdpPercap

  gapminder %>%
    group_by(country) %>%
    mutate(max_gdpPercap = max(gdpPercap)) %>%
    filter(max_gdpPercap == gdpPercap)

  ## Arrange()

  gapminder %>%
    group_by(country) %>%
    mutate(max_gdpPercap = max(gdpPercap)) %>%
    filter(max_gdpPercap == gdpPercap) %>%
    arrange(max_gdpPercap)

  gapminder %>%
    group_by(country) %>%
    mutate(max_gdpPercap = max(gdpPercap)) %>%
    filter(max_gdpPercap == gdpPercap) %>%
    arrange(desc(max_gdpPercap))
```

## Color Scatterplot

```{r color}
ggplot(data = mpg, aes(x = displ, y = hwy)) +
    geom_point(aes(color = class))
```

## Shape Scatterplot

```{r shape}
ggplot(data = mpg, aes(x = displ, y = hwy, shape = class)) +
    geom_point()
```

## Size Scatterplot

```{r size}
ggplot(data = mpg, aes(x = cty, y = hwy, size = class, color = fl)) + geom_point(alpha = 0.2)

```

## Jitterplot

```{r geom_examples}
  
ggplot(mpg, aes(x = drv,y = hwy)) + geom_jitter()

```

## Scatterplot with Line

```{r smooth line}

ggplot(data = mpg) + 
  geom_point(aes(x = displ, y = hwy), color="orange") +
  geom_smooth(aes(x = displ, y = hwy), color="black") + 
  labs(x = "Highway MPG", 
       y = "Engine Displacement (L)") + 
  theme_bw() + 
  theme(text=element_text(size = 14)) 
```